# SPDX-FileCopyrightText: 2021 - 2023
# - Nils Brinckmann <nils.brinckmann@gfz-potsdam.de>
# - Helmholtz Centre Potsdam - GFZ German Research Centre for Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# SPDX-License-Identifier: HEESIL-1.0

# Web client of the Sensor Management System software developed within
# the Helmholtz DataHub Initiative by GFZ and UFZ.
# 
# Copyright (C) 2020-2022
# - Wilhelm Becker (GFZ, wilhelm.becker@gfz-potsdam.de)
# - Nils Brinckmann (GFZ, nils.brinckmann@gfz-potsdam.de)
# - Marc Hanisch (GFZ, marc.hanisch@gfz-potsdam.de)
# - Helmholtz Centre Potsdam - GFZ German Research Centre for
#   Geosciences (GFZ, https://www.gfz-potsdam.de)
# 
# Parts of this program were developed within the context of the
# following publicly funded projects or measures:
# - Helmholtz Earth and Environment DataHub
#   (https://www.helmholtz.de/en/research/earth_and_environment/initiatives/#h51095)
# 
# Licensed under the HEESIL, Version 1.0 or - as soon they will be 
# approved by the "Community" - subsequent versions of the HEESIL 
# (the "Licence").
# 
# You may not use this work except in compliance with the Licence.
# 
# You may obtain a copy of the Licence at: 
# https://gitext.gfz-potsdam.de/software/heesil
# 
# Unless required by applicable law or agreed to in writing, software 
# distributed under the Licence is distributed on an "AS IS" basis, 
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or 
# implied. See the Licence for the specific language governing 
# permissions and limitations under the Licence.
version : '3.3'

services:
  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:gfz-${CI_COMMIT_TAG:-prod-latest}
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8443:8443
    volumes:
      - /etc/ssl/gfz_hosts_default.chained.crt:/etc/ssl/default.crt:ro
      - /etc/ssl/private/gfz_hosts_default.key:/etc/ssl/private/default.key:ro
      - /etc/ssl/dhparam.pem:/etc/ssl/dhparam.pem:ro
      - /etc/ssl/dfn-ca-global-g2-chain.pem:/etc/ssl/chain.pem:ro
      - backend-static-files:/usr/share/nginx/html/static/backend:ro
      - idl-static-files:/usr/share/nginx/html/static/idl:ro
    networks:
      - nginx

  idl:
    image: registry.hzdr.de/hub-terra/sms/gfz-idl/backend:0.3
    restart: unless-stopped
    environment:
      DJANGO_DEBUG: 'false'
      DJANGO_ALLOWED_HOSTS: 'https://sensors.gfz-potsdam.de https://sensor.gfz-potsdam.de https://rz-vm257.gfz-potsdam.de http://sensor.gfz-potsdam.de idl'
      DJANGO_BASE_PATH: idl/
      DJANGO_STATIC_URL: /static/idl/
      DJANGO_STATIC_ROOT: /static/idl/
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_NAME: idl
      DJANGO_DB_USER: $IDL_DB_USER
      DJANGO_DB_PASSWORD: $IDL_DB_PASSWORD
      DJANGO_DB_HOST: idl-db
      DJANGO_DB_PORT: 5432
      IDL_TOKEN: $IDL_TOKEN
      OIDC_WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      VO_ADMIN_CONVENTIONS: '*:gfz-sms-admin'
      VO_MEMBER_CONVENTIONS: 'gfz:*,*:gfz-sms-member'
    volumes:
      - idl-static-files:/static/idl
    networks:
      - nginx
      - idl-db

  idl-db:
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $IDL_DB_PASSWORD
      POSTGRES_USER: $IDL_DB_USER
      POSTGRES_DB: idl
    volumes:
      - "idl-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - idl-db

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend
  
  minio:
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    restart: unless-stopped
    volumes:
      - minio-data:/data/minio
    networks:
      - nginx
      - backend
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    #      To deactivate the console
    #      MINIO_BROWSER: "off"
    command: server /data/minio --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: ${CI_REGISTRY_IMAGE}/mc:gfz-${CI_COMMIT_TAG:-prod-latest}
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    depends_on:
      - minio
    networks:
      - backend
    entrypoint: ['/create_bucket.sh']

  backend-db:
    image: postgis/postgis:12-3.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $BACKEND_DB_PASSWORD
      POSTGRES_USER: $BACKEND_DB_USER
      POSTGRES_DB: backend
    volumes:
      - "backend-db-data:/var/lib/postgresql/data"
    shm_size: 128M
    networks:
      - backend

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:gfz-${CI_COMMIT_TAG:-prod-latest}
    restart: unless-stopped
    environment:
      URL_PREFIX: /backend/api/v1
      STATIC_URL: /static/backend
      APP_SETTINGS: project.config.ProductionConfig
      DATABASE_URL: postgresql://${BACKEND_DB_USER}:${BACKEND_DB_PASSWORD}@backend-db:5432/backend
      OIDC_USERNAME_CLAIM: eduperson_principal_name
      WELL_KNOWN_URL: https://login.helmholtz.de/oauth2/.well-known/openid-configuration
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: sms-attachments
      MINIO_ENDPOINT: minio:9000
      DOWNLOAD_ENDPOINT: https://sensors.gfz-potsdam.de
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      ALLOWED_MIME_TYPES: ${ALLOWED_MIME_TYPES}
      ELASTICSEARCH_URL: http://elastic-search:9200
      HTTP_ORIGINS: ${HTTP_ORIGINS}
      SMS_IDL_TOKEN: $IDL_TOKEN
      IDL_URL: http://idl:8000/idl/api/idl
      CV_URL: https://sms-cv.helmholtz.cloud/sms/cv/api/v1
      SMS_BACKEND_URL: /backend/api/v1
      PKCE_CLIENT_ID: ${PKCE_CLIENT_ID}
      PKCE_SCOPES: profile openid email eduperson_principal_name
      INSTITUTE: gfz
      SMS_FRONTEND_URL: https://sensors.gfz-potsdam.de
      SMS_VERSION: ${SMS_VERSION}
      B2INST_TOKEN: ${B2INST_TOKEN}
      B2INST_URL: https://b2inst.gwdg.de
      B2INST_COMMUNITY: DataHub-Helmholtz-RF-EE
    depends_on:
      - backend-db
    volumes:
      - backend-static-files:/usr/src/app/project/static
    networks:
      - backend
      - nginx

volumes:
  idl-db-data:
  idl-static-files:
  elasticsearch-data:
  minio-data:
  backend-db-data:
  backend-static-files:
networks:
  nginx:
  backend:
  idl-db:
    
