# SPDX-FileCopyrightText: 2022 - 2024
# - Kotyba Alhaj Taha <kotyba.alhaj-taha@ufz.de>
# - Helmholtz Centre for Environmental Research GmbH - UFZ (UFZ, https://www.ufz.de)
#
# SPDX-License-Identifier: EUPL-1.2


version: "3"

services:

  # A helper container to generate self-signed SSL certificates
  icessl:
    build: ./icessl
    volumes:
      - "./icessl:/icessl:rw${VOLOPTS-}"
    command: python3 ice-ca-certs.py
