# Web client of the Sensor Management System software developed within
# the Helmholtz DataHub Initiative by GFZ and UFZ.
#
# Copyright (C) 2020-2021
# - Kotyba Alhaj Taha (UFZ, kotyba.alhaj-taha@ufz.de)
# - Nils Brinckmann (GFZ, nils.brinckmann@gfz-potsdam.de)
# - Maximilian Schaldach (UFZ, maximilian.schaldach@ufz.de)
# - Helmholtz Centre for Environmental Research GmbH - UFZ
#   (UFZ, https://www.ufz.de)
# - Helmholtz Centre Potsdam - GFZ German Research Centre for
#   Geosciences (GFZ, https://www.gfz-potsdam.de)
#
# Parts of this program were developed within the context of the
# following publicly funded projects or measures:
# - Helmholtz Earth and Environment DataHub
#   (https://www.helmholtz.de/en/research/earth_and_environment/initiatives/#h51095)
#
# Licensed under the HEESIL, Version 1.0 or - as soon they will be
# approved by the "Community" - subsequent versions of the HEESIL
# (the "Licence").
#
# You may not use this work except in compliance with the Licence.
#
# You may obtain a copy of the Licence at:
# https://gitext.gfz-potsdam.de/software/heesil
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licence is distributed on an "AS IS" basis,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the Licence for the specific language governing
# permissions and limitations under the Licence.

version: '3.9'
services:

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    container_name: sms_es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Dlog4j2.formatMsgNoLookups=true"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - sms

  backend:
    image: python:3.9-slim-buster
    container_name: sms_backend
    working_dir: /usr/src/app
    volumes:
      - './backend/app:/usr/src/app'
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      URL_PREFIX: ${URL_PREFIX:-/backend/rdm/svm-api/v1}
      STATIC_URL: ${STATIC_URL:-/static/backend}
      APP_SETTINGS: ${APP_SETTINGS:-project.config.DevelopmentConfig}
      ELASTICSEARCH_URL: ${ELASTICSEARCH_URL:-http://elastic-search:9200}
      DATABASE_URL: ${DATABASE_URL:-postgresql://postgres:postgres@db:5433/db_dev}
      DATABASE_TEST_URL: ${DATABASE_TEST_URL:-postgresql://postgres:postgres@db:5433/db_test}
      OIDC_USERNAME_CLAIM: ${OIDC_USERNAME_CLAIM:-sub}
      HTTP_ORIGINS: ${HTTP_ORIGINS:-https://localhost.localdomain}
      WELL_KNOWN_URL: ${WELL_KNOWN_URL:-https://webapp.ufz.de/idp/oidc/v1/.well-known/openid-configuration}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-admin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
      MINIO_SECURE: ${MINIO_SECURE:-False}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME:-sms-attachments}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT:-minio:9000}
      DOWNLOAD_ENDPOINT: ${DOWNLOAD_ENDPOINT:-https://localhost.localdomain}
      ALLOWED_MIME_TYPES: ${ALLOWED_MIME_TYPES:-image/png,application/pdf}
      IDL_URL: ${IDL_URL}
      SMS_IDL_TOKEN: ${SMS_IDL_TOKEN}
      CV_URL: ${CV_URL}
      INSTITUTE: ${INSTITUTE:-ufz}
      PKCE_SCOPES: ${NUXT_ENV_SCOPE:-openid profile email}
      SMS_BACKEND_URL: ${SMS_BACKEND_URL:-https://localhost.localdomain/backend/api/v1}
      PKCE_CLIENT_ID: ${NUXT_ENV_CLIENT_ID:-rdmsvm-implicit-flow}
      SMS_FRONTEND_URL: ${SMS_FRONTEND_URL:-https://localhost.localdomain}
      PID_SERVICE_URL: ${PID_SERVICE_URL:-http://vm04.pid.gwdg.de:8081/handles/21.T11998/}
      PID_SERVICE_USER: ${PID_SERVICE_USER}
      PID_SERVICE_PASSWORD: ${PID_SERVICE_PASSWORD}
      SCHEMA_VERSION: ${SCHEMA_VERSION:-0.1}
      IDENTIFIER_TYPE: ${IDENTIFIER_TYPE:-Handler}
      PID_SUFFIX: ${PID_SUFFIX:-SMS}
    depends_on:
      - db
    command: >
      sh -c "
      apt-get update && apt-get install -y  --no-install-recommends \
        gcc \
        libssl-dev \
        libffi-dev \
        musl-dev \
        cargo \
      && apt-get clean
      && pip install --no-cache-dir --upgrade pip
      && pip install --no-cache-dir -r requirements.txt
      && python manage.py db upgrade
      && gunicorn -b 0.0.0.0:5000 manage:app --reload --log-level debug --timeout 50
      "
    networks:
      - sms

  db:
    image: postgres:12-alpine
    container_name: sms_db
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ./backend/app/project/db/create.sql:/docker-entrypoint-initdb.d/create.sql
    networks:
      - sms
    command: -p 5433

  vocabulary:
    image: python:3-alpine
    container_name: sms_cv
    working_dir: /usr/cv/app
    volumes:
      - './sms-cv/src:/usr/cv/app'
      - static-files:/static/cv
    ports:
      - 8000:8000
    environment:
      CV_BASE_URL: ${CV_BASE_URL:-cv/}
      STATIC_URL: '/static/cv/'
      STATIC_ROOT: '/static/cv/'
      DEBUG: ${DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-TopSecret}
      SQL_ENGINE: ${SQL_ENGINE:-django.db.backends.postgresql_psycopg2}
      SQL_DATABASE: ${SQL_DATABASE:-postgres}
      SQL_USER: ${SQL_USER:-postgres}
      SQL_PASSWORD: ${SQL_PASSWORD:-postgres}
      SQL_HOST: ${SQL_HOST:-db}
      SQL_PORT: ${SQL_PORT:-5433}
      CORS_ORIGIN_WHITELIST: ${CORS_ORIGIN_WHITELIST:-https://localhost.localdomain}
    command: >
      sh -c "
      apk add --no-cache --virtual .build-deps \
          gcc \
          python3-dev \
          musl-dev \
          postgresql-dev \
      && pip install --upgrade pip
      && pip install -r requirements.txt
      && python manage.py migrate
      && python manage.py loaddata initial_data.json
      && python manage.py loaddata default_community_data.json
      && python manage.py loaddata hydro_community_data.json
      && python manage.py collectstatic --noinput
      && gunicorn cv.wsgi:application --bind 0:8000 --reload --log-level debug --timeout 50
            "
    networks:
      - sms
    depends_on:
      - db

  frontend:
    build:
      context: '.'
      dockerfile: './frontend/docker/local-dev/Dockerfile-local-dev'
    container_name: sms_frontend
    working_dir: /home/node/
    user: "node"
    networks:
      - sms
    ports:
      - 3000:3000
    environment:
      BASE_URL: ${BASE_URL:-/}
      SMS_BACKEND_URL: ${SMS_BACKEND_URL:-https://localhost.localdomain/backend/rdm/svm-api/v1}
      CV_BACKEND_URL: ${CV_BACKEND_URL:-/cv/api/v1}
      NUXT_ENV_REDIRECT_URI: ${NUXT_ENV_REDIRECT_URI:-https://localhost.localdomain/login-callback}
      NUXT_ENV_CLIENT_ID: ${NUXT_ENV_CLIENT_ID:-rdmsvm-implicit-flow}
      # We reuse here the variable defined for the backend
      NUXT_ENV_OIDC_WELL_KNOWN: ${WELL_KNOWN_URL:-https://webapp.ufz.de/idp/oidc/v1/.well-known/openid-configuration}
      STAY_WITH_HTTP: ${STAY_WITH_HTTP:-true }
      NUXT_ENV_ALLOWED_MIMETYPES: ${ALLOWED_MIME_TYPES:-image/png,application/pdf}
      NUXT_ENV_SCOPE: ${NUXT_ENV_SCOPE:-openid profile email}
      NUXT_ENV_OIDC_SCHEME: ${NUXT_ENV_OIDC_SCHEME}
      NUXT_ENV_OIDC_REFRESH_TOKEN: ${NUXT_ENV_OIDC_REFRESH_TOKEN}
      NUXT_ENV_OIDC_REFRESH_EXPIRE: ${NUXT_ENV_OIDC_REFRESH_EXPIRE}
      NUXT_ENV_OIDC_RESPONSE_TYPE: ${NUXT_ENV_OIDC_RESPONSE_TYPE}
      NUXT_ENV_OIDC_GRANT_TYPE: ${NUXT_ENV_OIDC_GRANT_TYPE}
      NUXT_ENV_OIDC_CHALLANGE: ${NUXT_ENV_OIDC_CHALLANGE}
      NUXT_ENV_OIDC_REFRESH_INTERVAL_TIME: ${NUXT_ENV_OIDC_REFRESH_INTERVAL_TIME}
      NUXT_ENV_OIDC_LOGIN_PARAMS: ${NUXT_ENV_OIDC_LOGIN_PARAMS}
      INSTITUTE: ${INSTITUTE:-ufz}
      IDL_SYNC_URL: ${IDL_SYNC_URL}
    volumes:
      - ./frontend/:/home/node/
      - ./frontend/dist:/home/node/dist/:rw
    command: >
      bash -c "npm install
      && npm run dev"

  minio:
    image: minio/minio:RELEASE.2021-08-05T22-01-19Z
    container_name: sms_minio
    volumes:
      - minio-data:/data/minio
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - sms
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-admin}
      MINIO_ROOT_PASSWORD: ${minio_user_password:-minio123}
    #       To deactivate the console
#      MINIO_BROWSER: "off"
    command: server /data/minio --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc:latest
    container_name: sms_mc
    depends_on:
      - minio
    networks:
      - sms
    # Make a Bucket using minio client mc
    # https://docs.min.io/docs/minio-client-complete-guid
    entrypoint: >
      /bin/sh -c "
      until curl -f http://minio:9000/minio/health/live; do sleep 5; done;
      /usr/bin/mc  alias set minio http://minio:9000 ${MINIO_ACCESS_KEY:-admin} ${MINIO_SECRET_KEY:-minio123} --api S3v4;
      /usr/bin/mc mb --quiet minio/${MINIO_BUCKET_NAME:-sms-attachments};
      /usr/bin/mc policy set download minio/${MINIO_BUCKET_NAME:-sms-attachments};
      exit 0;
      "

  nginx:
    image: nginx:1.20-alpine
    container_name: sms_web
    ports:
      - 443:443
      - 8443:8443
    networks:
      - sms
    volumes:
      - ./nginx/certs:/etc/nginx/ssl
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/etc/nginx/html
      - static-files:/usr/share/nginx/html/static/cv:ro
      - ./backend/app/project/static:/usr/share/nginx/html/static/backend:ro
    depends_on:
      - frontend
      - minio
      - vocabulary
      - backend


volumes:
  esdata01:
    driver: local
  minio-data: {}
  static-files: {}

networks:
  sms:
    name: sms-docker-network