---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-production
  namespace: sms-cv-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sms-administration@ufz.de
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - http01:
          ingress:
            class: nginx
